### ISSUE TITLE
making `debug` part of a #lang reader by default

### ISSUE THREAD

**Issue by mbutterick** [AlexKnauth/debug#19]
I would like to make the `debug` metareader part of the default `#lang br` environment (that is, `#lang br` would work the way `#lang debug br` does now). Roughly, how might I do this with the current `debug` interface? Or would it require some form of cooperation not yet available?

**Comment by AlexKnauth** [comment]
Do you mean make `br` such that new `#lang br` is equivalent to current `#lang debug br`?

**Comment by AlexKnauth** [comment]
You should be able to use `wrap-reader` from `debug/reader`. Although that's not currently documented, maybe it should be.

**Comment by mbutterick** [comment]
OK, I’ll try that and see how far I get.

**Comment by mbutterick** [comment]
My new `#lang br` reader module looks like so:

```racket
(module reader syntax/module-reader
  #:language 'br
  #:info br-get-info
  #:read br-read
  #:read-syntax br-read-syntax
  (require br/get-info debug/lang/reader (prefix-in at: scribble/reader))
  (define br-read (wrap-reader at:read))
  (define br-read-syntax (wrap-reader at:read-syntax)))
```

But I get an error when I try to use #R in a `#lang br` module:

```
git/debug/debug/lang/reader.rkt:63:12: let: identifier's binding is ambiguous
  context...:
  matching binding...:
  matching binding...: in: let
```

Any idea how to fix this? I assume it’s a consequence of the vigorous scope manipulation.

**Comment by AlexKnauth** [comment]
That’s probably coming from my hack way of trying to make reader-extensions hygienic. I’m away from my computer right now, but I’m curious how this works so I’ll try to figure it out.

**Comment by AlexKnauth** [comment]
I think I've figured it out. The `wrap-reader` uses a parameter to keep track of the current-syntax-introducer, and the value of that parameter is different every time the result procedure is called.

This could possibly be fixed in either of two ways:
  1. Use `wrap-reader` on the whole-module read function that would be exported by the reader module, not the single-expression read function like `at:read-syntax` that you deal with within `syntax/module-reader` or normal use.
  2. Or change `wrap-reader` to use a single value of current-syntax-introducer for all calls to the result function (not working so far).

The first method would look like this, and you could use it right away:
```racket
(module reader racket/base
  (provide (rename-out
            [br-read read]
            [br-read-syntax read-syntax]
            [sub:get-info get-info]))

  (module sub-reader syntax/module-reader
    #:language 'br
    #:info br-get-info
    #:read at:read
    #:read-syntax at:read-syntax
    (require br/get-info (prefix-in at: scribble/reader)))

  (require debug/reader
           (prefix-in sub: 'sub-reader))

  (define br-read (wrap-reader sub:read))
  (define br-read-syntax (wrap-reader sub:read-syntax)))
```

The second method would require me to change `debug`'s `wrap-reader` function to share state between all calls to the result function. My initial attempts to do this have failed. I don't know why, but my hunch is that the small single-expression-at-a-time readers that `syntax/module-reader` deals with don't have control over the whole module, and in particular don't have control over the scopes introduced on the module-language AKA the `modlang` in `(module name modlang body ...)`. That might cause an ambiguous binding conflict between `modlang` and my reader module. The whole-module readers exported from a reader module don't have this problem because the reader controls which scopes the `modlang` gets.

So for now, the first method is the best I've got.

**Comment by mbutterick** [comment]
That works just fine. Thanks.
